-- =============================================================
-- DENLIFE TAM KURULUM SQL
-- Mevcut verileri silmez. Eksik tablo/sütunları tamamlar.
-- Supabase > SQL Editor > New query alanında bir kez çalıştırın.
-- =============================================================

-- KATEGORİLER
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text,
  icon text,
  created_at timestamptz default now()
);
alter table public.categories add column if not exists slug text;
alter table public.categories add column if not exists icon text;
alter table public.categories add column if not exists created_at timestamptz default now();
create unique index if not exists categories_name_uidx on public.categories(name);
create unique index if not exists categories_slug_uidx on public.categories(slug) where slug is not null;

-- KAYNAKLAR
create table if not exists public.sources (
  id bigint generated by default as identity primary key,
  name text not null,
  website_url text,
  source_type text default 'official',
  is_active boolean default true,
  created_at timestamptz default now()
);
alter table public.sources add column if not exists website_url text;
alter table public.sources add column if not exists source_type text default 'official';
alter table public.sources add column if not exists is_active boolean default true;
alter table public.sources add column if not exists created_at timestamptz default now();
create index if not exists sources_name_idx on public.sources(name);

-- ETKİNLİK MEKANLARI
create table if not exists public.venues (
  id bigint generated by default as identity primary key,
  name text not null,
  district text,
  address text,
  latitude double precision,
  longitude double precision,
  maps_url text,
  website_url text,
  phone text,
  created_at timestamptz default now()
);
alter table public.venues add column if not exists district text;
alter table public.venues add column if not exists address text;
alter table public.venues add column if not exists latitude double precision;
alter table public.venues add column if not exists longitude double precision;
alter table public.venues add column if not exists maps_url text;
alter table public.venues add column if not exists website_url text;
alter table public.venues add column if not exists phone text;
alter table public.venues add column if not exists created_at timestamptz default now();
create index if not exists venues_name_idx on public.venues(name);

-- ETKİNLİKLER
create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null,
  description text,
  category_id bigint references public.categories(id),
  venue_id bigint references public.venues(id),
  source_id bigint references public.sources(id),
  start_at timestamptz not null,
  end_at timestamptz,
  image_url text,
  ticket_url text,
  source_url text,
  price_min numeric(10,2),
  price_max numeric(10,2),
  is_free boolean default false,
  status text default 'published',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.events add column if not exists description text;
alter table public.events add column if not exists category_id bigint references public.categories(id);
alter table public.events add column if not exists venue_id bigint references public.venues(id);
alter table public.events add column if not exists source_id bigint references public.sources(id);
alter table public.events add column if not exists end_at timestamptz;
alter table public.events add column if not exists image_url text;
alter table public.events add column if not exists ticket_url text;
alter table public.events add column if not exists source_url text;
alter table public.events add column if not exists price_min numeric(10,2);
alter table public.events add column if not exists price_max numeric(10,2);
alter table public.events add column if not exists is_free boolean default false;
alter table public.events add column if not exists status text default 'published';
alter table public.events add column if not exists created_at timestamptz default now();
alter table public.events add column if not exists updated_at timestamptz default now();
create unique index if not exists events_slug_uidx on public.events(slug);
create index if not exists events_start_at_idx on public.events(start_at);
create index if not exists events_category_id_idx on public.events(category_id);
create index if not exists events_source_id_idx on public.events(source_id);

-- ŞEHİR REHBERİ MEKANLARI
create table if not exists public.places (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  category text not null default 'gezilecek-yer',
  description text,
  district text,
  address text,
  latitude double precision,
  longitude double precision,
  phone text,
  website_url text,
  maps_url text,
  image_url text,
  opening_hours text,
  source_name text,
  source_url text,
  external_id text,
  is_featured boolean default false,
  status text default 'published',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.places add column if not exists category text default 'gezilecek-yer';
alter table public.places add column if not exists description text;
alter table public.places add column if not exists district text;
alter table public.places add column if not exists address text;
alter table public.places add column if not exists latitude double precision;
alter table public.places add column if not exists longitude double precision;
alter table public.places add column if not exists phone text;
alter table public.places add column if not exists website_url text;
alter table public.places add column if not exists maps_url text;
alter table public.places add column if not exists image_url text;
alter table public.places add column if not exists opening_hours text;
alter table public.places add column if not exists source_name text;
alter table public.places add column if not exists source_url text;
alter table public.places add column if not exists external_id text;
alter table public.places add column if not exists is_featured boolean default false;
alter table public.places add column if not exists status text default 'published';
alter table public.places add column if not exists created_at timestamptz default now();
alter table public.places add column if not exists updated_at timestamptz default now();
create unique index if not exists places_slug_uidx on public.places(slug);
create index if not exists places_category_idx on public.places(category);
create index if not exists places_district_idx on public.places(district);
create index if not exists places_external_id_idx on public.places(external_id);
create index if not exists places_source_name_idx on public.places(source_name);

-- RLS
alter table public.categories enable row level security;
alter table public.sources enable row level security;
alter table public.venues enable row level security;
alter table public.events enable row level security;
alter table public.places enable row level security;

do $$ begin
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='categories' and policyname='Public categories are readable') then
    create policy "Public categories are readable" on public.categories for select to anon, authenticated using (true);
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='venues' and policyname='Public venues are readable') then
    create policy "Public venues are readable" on public.venues for select to anon, authenticated using (true);
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='events' and policyname='Published events are readable') then
    create policy "Published events are readable" on public.events for select to anon, authenticated using (status='published');
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='places' and policyname='Published places are readable') then
    create policy "Published places are readable" on public.places for select to anon, authenticated using (status='published');
  end if;
end $$;

-- ETKİNLİK KATEGORİLERİ
insert into public.categories(name,slug,icon) values
('Konser','konser','🎵'),('Tiyatro','tiyatro','🎭'),('Festival','festival','🎉'),('Sinema','sinema','🎬'),
('Sergi','sergi','🎨'),('Spor','spor','⚽'),('Çocuk','cocuk','🧸'),('Atölye','atolye','🛠️'),
('Söyleşi','soylesi','🎤'),('Sempozyum','sempozyum','🎓'),('Seminer','seminer','📚'),('Panel','panel','💬'),
('Konferans','konferans','🎙️'),('Çalıştay','calistay','🧩'),('Eğitim','egitim','📖'),('Yarışma','yarisma','🏆'),('Diğer','diger','📍')
on conflict(name) do update set slug=excluded.slug,icon=excluded.icon;

-- RESMİ KAYNAKLAR
insert into public.sources(name,website_url,source_type,is_active)
select 'Pamukkale Üniversitesi','https://www.pau.edu.tr/','official',true
where not exists(select 1 from public.sources where name='Pamukkale Üniversitesi');
insert into public.sources(name,website_url,source_type,is_active)
select 'Denizli Büyükşehir Belediyesi','https://www.denizli.bel.tr/','official',true
where not exists(select 1 from public.sources where name='Denizli Büyükşehir Belediyesi');

-- BAŞLANGIÇ MEKANLARI: site ilk açılışta boş kalmasın
insert into public.places(name,slug,category,description,district,source_name,source_url,is_featured) values
('Pamukkale - Hierapolis','pamukkale-hierapolis','tarihi-yer','Pamukkale travertenleri ve Hierapolis Antik Kenti çevresindeki önemli ziyaret alanı.','Pamukkale','Denizli İl Kültür ve Turizm Müdürlüğü','https://denizli.ktb.gov.tr/',true),
('Laodikeia Antik Kenti','laodikeia-antik-kenti','tarihi-yer','Denizli’nin önemli antik kentlerinden Laodikeia örenyeri.','Pamukkale','Denizli İl Kültür ve Turizm Müdürlüğü','https://denizli.ktb.gov.tr/',true),
('Denizli Kent Müzesi','denizli-kent-muzesi','tarihi-yer','Denizli’nin kent belleği, kültürü ve tarihine odaklanan müze.','Merkezefendi','Denizli İl Kültür ve Turizm Müdürlüğü','https://denizli.ktb.gov.tr/',true),
('Karahayıt Kırmızı Su Travertenleri','karahayit-kirmizi-su-travertenleri','gezilecek-yer','Karahayıt’taki termal su kaynakları ve kırmızı renkli traverten oluşumları.','Pamukkale','Denizli İl Kültür ve Turizm Müdürlüğü','https://denizli.ktb.gov.tr/',true),
('Kaklık Mağarası','kaklik-magarasi','gezilecek-yer','Denizli’nin öne çıkan doğal ziyaret noktalarından Kaklık Mağarası.','Honaz','Denizli İl Kültür ve Turizm Müdürlüğü','https://denizli.ktb.gov.tr/',false),
('Buldan Tarihi Evleri ve Çarşısı','buldan-tarihi-evleri','gezilecek-yer','Geleneksel dokusu ve dokumacılık kültürüyle öne çıkan Buldan tarihi merkezi.','Buldan','Denizli İl Kültür ve Turizm Müdürlüğü','https://denizli.ktb.gov.tr/',false),
('Çamlık Parkı','camlik-parki','park','Denizli’de yürüyüş ve açık hava için tercih edilen geniş yeşil alanlardan biri.','Pamukkale','DENLIFE başlangıç verisi','https://www.google.com/maps/search/?api=1&query=%C3%87aml%C4%B1k+Park%C4%B1+Denizli',true),
('İncilipınar Parkı','incilipinar-parki','park','Merkezefendi’de dinlenme ve yürüyüş için şehir parkı.','Merkezefendi','DENLIFE başlangıç verisi','https://www.google.com/maps/search/?api=1&query=%C4%B0ncilip%C4%B1nar+Park%C4%B1+Denizli',false),
('Denizli Teleferik ve Bağbaşı Yaylası','denizli-teleferik-bagbasi','gezilecek-yer','Şehir manzarası ve yayla deneyimi için Denizli’nin öne çıkan gezi noktalarından biri.','Pamukkale','DENLIFE başlangıç verisi','https://www.google.com/maps/search/?api=1&query=Denizli+Teleferik+Ba%C4%9Fba%C5%9F%C4%B1',true),
('Honaz Dağı Milli Parkı','honaz-dagi-milli-parki','gezilecek-yer','Doğa yürüyüşü ve açık hava aktiviteleri için önemli doğal alan.','Honaz','DENLIFE başlangıç verisi','https://www.google.com/maps/search/?api=1&query=Honaz+Da%C4%9F%C4%B1+Milli+Park%C4%B1',false),
('Forum Çamlık AVM','forum-camlik-avm','alisveris','Pamukkale’de alışveriş, yeme içme ve eğlence seçenekleri sunan alışveriş merkezi.','Pamukkale','DENLIFE başlangıç verisi','https://www.google.com/maps/search/?api=1&query=Forum+%C3%87aml%C4%B1k+AVM+Denizli',false),
('Teras Park Alışveriş Merkezi','teras-park-avm','alisveris','Merkezefendi’de alışveriş ve sosyal yaşam merkezi.','Merkezefendi','DENLIFE başlangıç verisi','https://www.google.com/maps/search/?api=1&query=Teras+Park+AVM+Denizli',false),
('The Parsons Coffee','the-parsons-coffee','kafe','Merkezefendi’de kahve ve kafe seçeneği.','Merkezefendi','DENLIFE başlangıç verisi','https://www.google.com/maps/search/?api=1&query=The+Parsons+Coffee+Denizli',false),
('Analog Plak & Kahve Evi Denizli','analog-plak-kahve-evi','kafe','Pamukkale Kınıklı’da kahve ve plak konseptli kafe.','Pamukkale','DENLIFE başlangıç verisi','https://www.google.com/maps/search/?api=1&query=Analog+Plak+Kahve+Evi+Denizli',false),
('Çamlık Denizli Kebapçısı','camlik-denizli-kebapcisi','restoran','Pamukkale Çamlık bölgesinde Denizli kebabı sunan restoran.','Pamukkale','DENLIFE başlangıç verisi','https://www.google.com/maps/search/?api=1&query=%C3%87aml%C4%B1k+Denizli+Kebap%C3%A7%C4%B1s%C4%B1',false),
('Garson Şükrü Aile Restaurant','garson-sukru-aile-restaurant','restoran','Denizli merkezde restoran seçeneği.','Merkezefendi','DENLIFE başlangıç verisi','https://www.google.com/maps/search/?api=1&query=Garson+%C5%9E%C3%BCkr%C3%BC+Denizli',false),
('Anemon Grand Denizli Otel','anemon-grand-denizli','otel','Merkezefendi’de konaklama seçeneği.','Merkezefendi','DENLIFE başlangıç verisi','https://www.google.com/maps/search/?api=1&query=Anemon+Grand+Denizli',false),
('Park Dedeman Denizli','park-dedeman-denizli','otel','Pamukkale’de konaklama seçeneği.','Pamukkale','DENLIFE başlangıç verisi','https://www.google.com/maps/search/?api=1&query=Park+Dedeman+Denizli',false),
('Denizli Atatürk Stadyumu','denizli-ataturk-stadyumu','spor','Denizli merkezde spor müsabakalarının düzenlendiği stadyum.','Merkezefendi','DENLIFE başlangıç verisi','https://www.google.com/maps/search/?api=1&query=Denizli+Atat%C3%BCrk+Stadyumu',false)
on conflict(slug) do update set
  category=excluded.category,description=excluded.description,district=excluded.district,
  source_name=excluded.source_name,source_url=excluded.source_url,is_featured=excluded.is_featured,updated_at=now();
