import type { ImportedPlace } from "./save-place";

// DENLIFE'ın ilk açılışta boş kalmaması için düşük riskli başlangıç verisi.
// Bu kayıtlar otomatik importer tarafından Supabase'e upsert edilir.
export const seedPlaces: ImportedPlace[] = [
  {
    name: "Pamukkale - Hierapolis",
    externalId: "seed-pamukkale-hierapolis",
    category: "tarihi-yer",
    description: "Pamukkale travertenleri ve Hierapolis Antik Kenti çevresindeki önemli ziyaret alanı.",
    district: "Pamukkale",
    sourceName: "Denizli İl Kültür ve Turizm Müdürlüğü",
    sourceUrl: "https://denizli.ktb.gov.tr/",
    openingHours: "Ziyaret saatleri dönemsel olarak değişebilir; resmi kaynağı kontrol edin.",
    featured: true,
  },
  {
    name: "Hierapolis Arkeoloji Müzesi",
    externalId: "seed-hierapolis-arkeoloji-muzesi",
    category: "tarihi-yer",
    description: "Hierapolis örenyeri içerisinde yer alan arkeoloji müzesi.",
    district: "Pamukkale",
    sourceName: "Denizli İl Kültür ve Turizm Müdürlüğü",
    sourceUrl: "https://denizli.ktb.gov.tr/",
    featured: true,
  },
  {
    name: "Laodikeia Antik Kenti",
    externalId: "seed-laodikeia",
    category: "tarihi-yer",
    description: "Denizli'nin önemli antik kentlerinden Laodikeia örenyeri.",
    district: "Pamukkale",
    sourceName: "Denizli İl Kültür ve Turizm Müdürlüğü",
    sourceUrl: "https://denizli.ktb.gov.tr/",
    featured: true,
  },
  {
    name: "Denizli Kent Müzesi",
    externalId: "seed-denizli-kent-muzesi",
    category: "tarihi-yer",
    description: "Denizli'nin kent belleği, kültürü ve tarihine odaklanan müze.",
    district: "Merkezefendi",
    sourceName: "Denizli İl Kültür ve Turizm Müdürlüğü",
    sourceUrl: "https://denizli.ktb.gov.tr/",
    featured: true,
  },
  {
    name: "Atatürk ve Etnografya Müzesi",
    externalId: "seed-ataturk-etnografya",
    category: "tarihi-yer",
    description: "Denizli merkezde ziyaret edilebilen müze ve etnografya alanı.",
    district: "Merkezefendi",
    sourceName: "Denizli İl Kültür ve Turizm Müdürlüğü",
    sourceUrl: "https://denizli.ktb.gov.tr/",
  },
  {
    name: "Karahayıt Kırmızı Su Travertenleri",
    externalId: "seed-karahayit-kirmizi-su",
    category: "gezilecek-yer",
    description: "Karahayıt'taki termal su kaynakları ve kırmızı renkli traverten oluşumları.",
    district: "Pamukkale",
    sourceName: "Denizli İl Kültür ve Turizm Müdürlüğü",
    sourceUrl: "https://denizli.ktb.gov.tr/",
    featured: true,
  },
  {
    name: "Kaklık Mağarası",
    externalId: "seed-kaklik-magarasi",
    category: "gezilecek-yer",
    description: "Denizli'nin öne çıkan doğal ziyaret noktalarından Kaklık Mağarası.",
    district: "Honaz",
    sourceName: "Denizli İl Kültür ve Turizm Müdürlüğü",
    sourceUrl: "https://denizli.ktb.gov.tr/",
  },
  {
    name: "Buldan Tarihi Evleri ve Çarşısı",
    externalId: "seed-buldan-evleri",
    category: "gezilecek-yer",
    description: "Geleneksel dokusu ve dokumacılık kültürüyle öne çıkan Buldan tarihi merkezi.",
    district: "Buldan",
    sourceName: "Denizli İl Kültür ve Turizm Müdürlüğü",
    sourceUrl: "https://denizli.ktb.gov.tr/",
  },
  {
    name: "Forum Çamlık AVM",
    externalId: "seed-forum-camlik",
    category: "alisveris",
    description: "Denizli Pamukkale'de alışveriş, yeme içme ve eğlence seçenekleri sunan alışveriş merkezi.",
    district: "Pamukkale",
    address: "Mehmetçik, Doğan Demircioğlu Cd. No:2, Pamukkale/Denizli",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Forum+%C3%87aml%C4%B1k+AVM+Denizli",
  },
  {
    name: "Teras Park Alışveriş Merkezi",
    externalId: "seed-teras-park",
    category: "alisveris",
    description: "Denizli Merkezefendi'de alışveriş ve sosyal yaşam merkezi.",
    district: "Merkezefendi",
    address: "Yenişehir, Denizli Merkezefendi/Denizli",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Teras+Park+AVM+Denizli",
  },
  {
    name: "Sinpaş Aquamall AVM",
    externalId: "seed-aquamall",
    category: "alisveris",
    description: "Denizli Merkezefendi'de alışveriş merkezi.",
    district: "Merkezefendi",
    address: "Kayalar, Menderes Blv. No:185, Merkezefendi/Denizli",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Sinpa%C5%9F+Aquamall+AVM+Denizli",
  },
  {
    name: "The Parsons Coffee",
    externalId: "seed-parsons-coffee",
    category: "kafe",
    description: "Merkezefendi'de kahve ve kafe seçeneği.",
    district: "Merkezefendi",
    address: "Selçukbey, Denizli Merkezefendi/Denizli",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=The+Parsons+Coffee+Denizli",
  },
  {
    name: "Analog Plak & Kahve Evi Denizli",
    externalId: "seed-analog-kahve",
    category: "kafe",
    description: "Pamukkale Kınıklı'da kahve ve plak konseptli kafe.",
    district: "Pamukkale",
    address: "Kınıklı, Kınıklı Cd., Pamukkale/Denizli",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Analog+Plak+Kahve+Evi+Denizli",
  },
  {
    name: "Filicori Coffee Kampüs",
    externalId: "seed-filicori-kampus",
    category: "kafe",
    description: "Pamukkale Kınıklı'da kahve seçeneği.",
    district: "Pamukkale",
    address: "Kınıklı, Pamukkale/Denizli",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Filicori+Coffee+Kamp%C3%BCs+Denizli",
  },
  {
    name: "Çamlık Denizli Kebapçısı",
    externalId: "seed-camlik-denizli-kebapcisi",
    category: "restoran",
    description: "Pamukkale Çamlık bölgesinde Denizli kebabı sunan restoran.",
    district: "Pamukkale",
    address: "Kınıklı, Çamlık Blv., Pamukkale/Denizli",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=%C3%87aml%C4%B1k+Denizli+Kebap%C3%A7%C4%B1s%C4%B1",
  },
  {
    name: "Garson Şükrü Aile Restaurant",
    externalId: "seed-garson-sukru",
    category: "restoran",
    description: "Denizli merkezde restoran seçeneği.",
    district: "Merkezefendi",
    address: "Gökpınar, Denizli",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Garson+%C5%9E%C3%BCkr%C3%BC+Denizli",
  },
  {
    name: "Anemon Grand Denizli Otel",
    externalId: "seed-anemon-grand",
    category: "otel",
    description: "Merkezefendi'de konaklama seçeneği.",
    district: "Merkezefendi",
    address: "Hacıeyüplü, İzmir Karayolu, Merkezefendi/Denizli",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Anemon+Grand+Denizli",
  },
  {
    name: "Park Dedeman Denizli",
    externalId: "seed-park-dedeman",
    category: "otel",
    description: "Pamukkale'de konaklama seçeneği.",
    district: "Pamukkale",
    address: "Karşıyaka, Pamukkale/Denizli",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Park+Dedeman+Denizli",
  },
  {
    name: "Grand Denizli Otel",
    externalId: "seed-grand-denizli-otel",
    category: "otel",
    description: "Denizli merkezde konaklama seçeneği.",
    district: "Merkezefendi",
    address: "Saraylar, Cumhuriyet Cd., Denizli",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Grand+Denizli+Otel",
  },

  {
    name: "Çamlık Parkı",
    externalId: "seed-camlik-parki",
    category: "park",
    description: "Denizli'de yürüyüş ve açık hava için tercih edilen geniş yeşil alanlardan biri.",
    district: "Pamukkale",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=%C3%87aml%C4%B1k+Park%C4%B1+Denizli",
    featured: true,
  },
  {
    name: "İncilipınar Parkı",
    externalId: "seed-incilipinar-parki",
    category: "park",
    description: "Merkezefendi'de dinlenme, yürüyüş ve açık hava için şehir parkı.",
    district: "Merkezefendi",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=%C4%B0ncilip%C4%B1nar+Park%C4%B1+Denizli",
  },
  {
    name: "Denizli Teleferik ve Bağbaşı Yaylası",
    externalId: "seed-teleferik-bagbasi",
    category: "gezilecek-yer",
    description: "Şehir manzarası ve yayla deneyimi için Denizli'nin öne çıkan gezi noktalarından biri.",
    district: "Pamukkale",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Denizli+Teleferik+Ba%C4%9Fba%C5%9F%C4%B1",
    featured: true,
  },
  {
    name: "Honaz Dağı Milli Parkı",
    externalId: "seed-honaz-dagi",
    category: "gezilecek-yer",
    description: "Doğa yürüyüşü ve açık hava aktiviteleri için Denizli'nin önemli doğal alanlarından biri.",
    district: "Honaz",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Honaz+Da%C4%9F%C4%B1+Milli+Park%C4%B1",
  },
  {
    name: "Denizli Atatürk Stadyumu",
    externalId: "seed-ataturk-stadyumu",
    category: "spor",
    description: "Denizli merkezde spor müsabakalarının düzenlendiği stadyum.",
    district: "Merkezefendi",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Denizli+Atat%C3%BCrk+Stadyumu",
  },
  {
    name: "PAÜ Spor Merkezi",
    externalId: "seed-pau-spor-merkezi",
    category: "spor",
    description: "Pamukkale Üniversitesi yerleşkesinde spor ve aktivite alanı.",
    district: "Pamukkale",
    sourceName: "DENLIFE başlangıç verisi",
    sourceUrl: "https://www.google.com/maps/search/?api=1&query=Pamukkale+%C3%9Cniversitesi+Spor+Merkezi",
  },
];
